/*
 Navicat Premium Data Transfer

 Source Server         : mysql
 Source Server Type    : MySQL
 Source Server Version : 80011
 Source Host           : 35.194.137.178:3306
 Source Schema         : subway

 Target Server Type    : MySQL
 Target Server Version : 80011
 File Encoding         : 65001

 Date: 04/12/2018 19:10:02
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for nodes
-- ----------------------------
DROP TABLE IF EXISTS `nodes`;
CREATE TABLE `nodes`  (
  `id` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `group` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `pinyinname` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `group`) USING BTREE,
  INDEX `id`(`id`) USING BTREE,
  INDEX `group`(`group`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of nodes
-- ----------------------------
INSERT INTO `nodes` VALUES ('七里庄', '九号线', NULL);
INSERT INTO `nodes` VALUES ('七里庄', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('七里庄', '十四号西段', NULL);
INSERT INTO `nodes` VALUES ('万寿路', '一号线', NULL);
INSERT INTO `nodes` VALUES ('万源街', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('三元桥', '十号线', NULL);
INSERT INTO `nodes` VALUES ('上地', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('东单', '一号线', NULL);
INSERT INTO `nodes` VALUES ('东单', '五号线', NULL);
INSERT INTO `nodes` VALUES ('东四', '五号线', NULL);
INSERT INTO `nodes` VALUES ('东四', '六号线', NULL);
INSERT INTO `nodes` VALUES ('东四十条', '二号线', NULL);
INSERT INTO `nodes` VALUES ('东夏园', '六号线', NULL);
INSERT INTO `nodes` VALUES ('东大桥', '六号线', NULL);
INSERT INTO `nodes` VALUES ('东湖渠', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('东直门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('东风北桥', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('中关村', '四号线', NULL);
INSERT INTO `nodes` VALUES ('丰台东大街', '九号线', NULL);
INSERT INTO `nodes` VALUES ('丰台南路', '九号线', NULL);
INSERT INTO `nodes` VALUES ('丰台科技园', '九号线', NULL);
INSERT INTO `nodes` VALUES ('丰台站', '十号线', NULL);
INSERT INTO `nodes` VALUES ('临河里', '八通线', NULL);
INSERT INTO `nodes` VALUES ('义和庄', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('九棵树', '八通线', NULL);
INSERT INTO `nodes` VALUES ('九龙山', '七号线', NULL);
INSERT INTO `nodes` VALUES ('九龙山', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('五棵松', '一号线', NULL);
INSERT INTO `nodes` VALUES ('五道口', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('亦庄文化园', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('亦庄桥', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('亮马桥', '十号线', NULL);
INSERT INTO `nodes` VALUES ('人民大学', '四号线', NULL);
INSERT INTO `nodes` VALUES ('什刹海', '八号线', NULL);
INSERT INTO `nodes` VALUES ('传媒大学', '八通线', NULL);
INSERT INTO `nodes` VALUES ('俸伯', '十五号', NULL);
INSERT INTO `nodes` VALUES ('健德门', '十号线', NULL);
INSERT INTO `nodes` VALUES ('光熙门', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('八宝山', '一号线', NULL);
INSERT INTO `nodes` VALUES ('八角游乐园', '一号线', NULL);
INSERT INTO `nodes` VALUES ('八里桥', '八通线', NULL);
INSERT INTO `nodes` VALUES ('公主坟', '一号线', NULL);
INSERT INTO `nodes` VALUES ('公主坟', '十号线', NULL);
INSERT INTO `nodes` VALUES ('公益西桥', '四号线', NULL);
INSERT INTO `nodes` VALUES ('六道口', '十五号', NULL);
INSERT INTO `nodes` VALUES ('六里桥', '九号线', NULL);
INSERT INTO `nodes` VALUES ('六里桥', '十号线', NULL);
INSERT INTO `nodes` VALUES ('六里桥东', '九号线', NULL);
INSERT INTO `nodes` VALUES ('关庄', '十五号', NULL);
INSERT INTO `nodes` VALUES ('军事博物馆', '一号线', NULL);
INSERT INTO `nodes` VALUES ('军事博物馆', '九号线', NULL);
INSERT INTO `nodes` VALUES ('农业展览馆', '十号线', NULL);
INSERT INTO `nodes` VALUES ('分钟寺', '十号线', NULL);
INSERT INTO `nodes` VALUES ('刘家窑', '五号线', NULL);
INSERT INTO `nodes` VALUES ('前门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('动物园', '四号线', NULL);
INSERT INTO `nodes` VALUES ('劲松', '十号线', NULL);
INSERT INTO `nodes` VALUES ('化工', '七号线', NULL);
INSERT INTO `nodes` VALUES ('北京南站', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('北京南站', '四号线', NULL);
INSERT INTO `nodes` VALUES ('北京大学东门', '四号线', NULL);
INSERT INTO `nodes` VALUES ('北京站', '二号线', NULL);
INSERT INTO `nodes` VALUES ('北京西站', '七号线', NULL);
INSERT INTO `nodes` VALUES ('北京西站', '九号线', NULL);
INSERT INTO `nodes` VALUES ('北土城', '八号线', NULL);
INSERT INTO `nodes` VALUES ('北土城', '十号线', NULL);
INSERT INTO `nodes` VALUES ('北宫门', '四号线', NULL);
INSERT INTO `nodes` VALUES ('北工大西门', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('北新桥', '五号线', NULL);
INSERT INTO `nodes` VALUES ('北沙滩', '十五号', NULL);
INSERT INTO `nodes` VALUES ('北海北', '六号线', NULL);
INSERT INTO `nodes` VALUES ('北苑', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('北苑路北', '五号线', NULL);
INSERT INTO `nodes` VALUES ('北运河东', '六号线', NULL);
INSERT INTO `nodes` VALUES ('北运河西', '六号线', NULL);
INSERT INTO `nodes` VALUES ('北邵洼', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('十三陵景区', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('十里堡', '六号线', NULL);
INSERT INTO `nodes` VALUES ('十里河', '十号线', NULL);
INSERT INTO `nodes` VALUES ('十里河', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('南八里庄', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('南楼梓庄', '七号线', NULL);
INSERT INTO `nodes` VALUES ('南法信', '十五号', NULL);
INSERT INTO `nodes` VALUES ('南礼士路', '一号线', NULL);
INSERT INTO `nodes` VALUES ('南邵', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('南锣鼓巷', '六号线', NULL);
INSERT INTO `nodes` VALUES ('双井', '七号线', NULL);
INSERT INTO `nodes` VALUES ('双井', '十号线', NULL);
INSERT INTO `nodes` VALUES ('双合', '七号线', NULL);
INSERT INTO `nodes` VALUES ('双桥', '八通线', NULL);
INSERT INTO `nodes` VALUES ('古城', '一号线', NULL);
INSERT INTO `nodes` VALUES ('同济南路', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('后沙峪', '十五号', NULL);
INSERT INTO `nodes` VALUES ('呼家楼', '六号线', NULL);
INSERT INTO `nodes` VALUES ('呼家楼', '十号线', NULL);
INSERT INTO `nodes` VALUES ('和平西桥', '五号线', NULL);
INSERT INTO `nodes` VALUES ('和平里北街', '五号线', NULL);
INSERT INTO `nodes` VALUES ('和平门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('善各庄', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('四惠', '一号线', NULL);
INSERT INTO `nodes` VALUES ('四惠', '八通线', NULL);
INSERT INTO `nodes` VALUES ('四惠东', '一号线', NULL);
INSERT INTO `nodes` VALUES ('回龙观', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('回龙观东大街', '八号线', NULL);
INSERT INTO `nodes` VALUES ('团结湖', '十号线', NULL);
INSERT INTO `nodes` VALUES ('园博园', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('园博园', '十四号西段', NULL);
INSERT INTO `nodes` VALUES ('国家图书馆', '九号线', NULL);
INSERT INTO `nodes` VALUES ('国家图书馆', '四号线', NULL);
INSERT INTO `nodes` VALUES ('国展', '十五号', NULL);
INSERT INTO `nodes` VALUES ('国贸', '一号线', NULL);
INSERT INTO `nodes` VALUES ('国贸', '十号线', NULL);
INSERT INTO `nodes` VALUES ('圆明园', '四号线', NULL);
INSERT INTO `nodes` VALUES ('土桥', '八通线', NULL);
INSERT INTO `nodes` VALUES ('垡头', '七号线', NULL);
INSERT INTO `nodes` VALUES ('复兴门', '一号线', NULL);
INSERT INTO `nodes` VALUES ('复兴门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('大井', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('大井', '十四号西段', NULL);
INSERT INTO `nodes` VALUES ('大屯路东', '五号线', NULL);
INSERT INTO `nodes` VALUES ('大屯路东', '十五号', NULL);
INSERT INTO `nodes` VALUES ('大望路', '一号线', NULL);
INSERT INTO `nodes` VALUES ('大望路', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('大瓦窑', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('大瓦窑', '十四号西段', NULL);
INSERT INTO `nodes` VALUES ('大红门', '十号线', NULL);
INSERT INTO `nodes` VALUES ('大葆台', '房山站', NULL);
INSERT INTO `nodes` VALUES ('大郊亭', '七号线', NULL);
INSERT INTO `nodes` VALUES ('大钟寺', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('天坛东门', '五号线', NULL);
INSERT INTO `nodes` VALUES ('天安门东', '一号线', NULL);
INSERT INTO `nodes` VALUES ('天安门西', '一号线', NULL);
INSERT INTO `nodes` VALUES ('天宫院', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('天通苑', '五号线', NULL);
INSERT INTO `nodes` VALUES ('天通苑北', '五号线', NULL);
INSERT INTO `nodes` VALUES ('天通苑南', '五号线', NULL);
INSERT INTO `nodes` VALUES ('太阳宫', '十号线', NULL);
INSERT INTO `nodes` VALUES ('奥体中心', '八号线', NULL);
INSERT INTO `nodes` VALUES ('奥林匹克公园', '八号线', NULL);
INSERT INTO `nodes` VALUES ('奥林匹克公园', '十五号', NULL);
INSERT INTO `nodes` VALUES ('孙河', '十五号', NULL);
INSERT INTO `nodes` VALUES ('安华桥', '八号线', NULL);
INSERT INTO `nodes` VALUES ('安定门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('安德里北街', '八号线', NULL);
INSERT INTO `nodes` VALUES ('安河桥北', '四号线', NULL);
INSERT INTO `nodes` VALUES ('安立路', '十五号', NULL);
INSERT INTO `nodes` VALUES ('安贞门', '十号线', NULL);
INSERT INTO `nodes` VALUES ('宋家庄', '五号线', NULL);
INSERT INTO `nodes` VALUES ('宋家庄', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('宋家庄', '十号线', NULL);
INSERT INTO `nodes` VALUES ('宣武门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('宣武门', '四号线', NULL);
INSERT INTO `nodes` VALUES ('将台', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('小红门', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('崇文门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('崇文门', '五号线', NULL);
INSERT INTO `nodes` VALUES ('崔各庄', '十五号', NULL);
INSERT INTO `nodes` VALUES ('巩华城', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('巴沟', '十号线', NULL);
INSERT INTO `nodes` VALUES ('常营', '六号线', NULL);
INSERT INTO `nodes` VALUES ('平乐园', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('平安里', '六号线', NULL);
INSERT INTO `nodes` VALUES ('平安里', '四号线', NULL);
INSERT INTO `nodes` VALUES ('平西府', '八号线', NULL);
INSERT INTO `nodes` VALUES ('广安门内', '七号线', NULL);
INSERT INTO `nodes` VALUES ('广渠门内', '七号线', NULL);
INSERT INTO `nodes` VALUES ('广渠门外', '七号线', NULL);
INSERT INTO `nodes` VALUES ('广阳城', '房山站', NULL);
INSERT INTO `nodes` VALUES ('建国门', '一号线', NULL);
INSERT INTO `nodes` VALUES ('建国门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('张自忠路', '五号线', NULL);
INSERT INTO `nodes` VALUES ('张郭庄', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('张郭庄', '十四号西段', NULL);
INSERT INTO `nodes` VALUES ('惠新西街北口', '五号线', NULL);
INSERT INTO `nodes` VALUES ('惠新西街南口', '五号线', NULL);
INSERT INTO `nodes` VALUES ('惠新西街南口', '十号线', NULL);
INSERT INTO `nodes` VALUES ('慈寿寺', '六号线', NULL);
INSERT INTO `nodes` VALUES ('慈寿寺', '十号线', NULL);
INSERT INTO `nodes` VALUES ('成寿寺', '十号线', NULL);
INSERT INTO `nodes` VALUES ('新宫', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('新街口', '四号线', NULL);
INSERT INTO `nodes` VALUES ('方庄', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('旧宫', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('昌平', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('昌平东关', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('昌平西山口', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('景泰', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('望京', '十五号', NULL);
INSERT INTO `nodes` VALUES ('望京', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('望京东', '十五号', NULL);
INSERT INTO `nodes` VALUES ('望京南', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('望京西', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('望京西', '十五号', NULL);
INSERT INTO `nodes` VALUES ('朝阳公园', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('朝阳门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('朝阳门', '六号线', NULL);
INSERT INTO `nodes` VALUES ('木樨地', '一号线', NULL);
INSERT INTO `nodes` VALUES ('朱辛庄', '八号线', NULL);
INSERT INTO `nodes` VALUES ('朱辛庄', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('来广营', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('林萃桥', '八号线', NULL);
INSERT INTO `nodes` VALUES ('果园', '八通线', NULL);
INSERT INTO `nodes` VALUES ('枣园', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('枣营', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('柳芳', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('桥湾', '七号线', NULL);
INSERT INTO `nodes` VALUES ('梨园', '八通线', NULL);
INSERT INTO `nodes` VALUES ('森林公园南门', '八号线', NULL);
INSERT INTO `nodes` VALUES ('次渠', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('次渠南', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('欢乐谷景区', '七号线', NULL);
INSERT INTO `nodes` VALUES ('永安里', '一号线', NULL);
INSERT INTO `nodes` VALUES ('永定门外', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('永泰庄', '八号线', NULL);
INSERT INTO `nodes` VALUES ('沙河', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('沙河高教园', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('泥洼', '十号线', NULL);
INSERT INTO `nodes` VALUES ('海淀五路居', '六号线', NULL);
INSERT INTO `nodes` VALUES ('海淀黄庄', '十号线', NULL);
INSERT INTO `nodes` VALUES ('海淀黄庄', '四号线', NULL);
INSERT INTO `nodes` VALUES ('清华东路西口', '十五号', NULL);
INSERT INTO `nodes` VALUES ('清源路', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('湾子', '七号线', NULL);
INSERT INTO `nodes` VALUES ('潘家园', '十号线', NULL);
INSERT INTO `nodes` VALUES ('潞城', '六号线', NULL);
INSERT INTO `nodes` VALUES ('火器营', '十号线', NULL);
INSERT INTO `nodes` VALUES ('灯市口', '五号线', NULL);
INSERT INTO `nodes` VALUES ('灵境胡同', '四号线', NULL);
INSERT INTO `nodes` VALUES ('焦化厂', '七号线', NULL);
INSERT INTO `nodes` VALUES ('牡丹园', '十号线', NULL);
INSERT INTO `nodes` VALUES ('物资学院路', '六号线', NULL);
INSERT INTO `nodes` VALUES ('玉泉路', '一号线', NULL);
INSERT INTO `nodes` VALUES ('王府井', '一号线', NULL);
INSERT INTO `nodes` VALUES ('珠市口', '七号线', NULL);
INSERT INTO `nodes` VALUES ('生命科学园', '昌平线', NULL);
INSERT INTO `nodes` VALUES ('生物医药基地', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('白堆子', '九号线', NULL);
INSERT INTO `nodes` VALUES ('白石桥南', '九号线', NULL);
INSERT INTO `nodes` VALUES ('白石桥南', '六号线', NULL);
INSERT INTO `nodes` VALUES ('百子湾', '七号线', NULL);
INSERT INTO `nodes` VALUES ('知春路', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('知春路', '十号线', NULL);
INSERT INTO `nodes` VALUES ('知春里', '十号线', NULL);
INSERT INTO `nodes` VALUES ('石榴庄', '十号线', NULL);
INSERT INTO `nodes` VALUES ('石门', '十五号', NULL);
INSERT INTO `nodes` VALUES ('磁器口', '七号线', NULL);
INSERT INTO `nodes` VALUES ('磁器口', '五号线', NULL);
INSERT INTO `nodes` VALUES ('科怡路', '九号线', NULL);
INSERT INTO `nodes` VALUES ('积水潭', '二号线', NULL);
INSERT INTO `nodes` VALUES ('稻田', '房山站', NULL);
INSERT INTO `nodes` VALUES ('立水桥', '五号线', NULL);
INSERT INTO `nodes` VALUES ('立水桥', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('立水桥南', '五号线', NULL);
INSERT INTO `nodes` VALUES ('管庄', '八通线', NULL);
INSERT INTO `nodes` VALUES ('篱笆房', '房山站', NULL);
INSERT INTO `nodes` VALUES ('红庙', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('纪家庙', '十号线', NULL);
INSERT INTO `nodes` VALUES ('经海路', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('肖村', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('育新', '八号线', NULL);
INSERT INTO `nodes` VALUES ('育知路', '八号线', NULL);
INSERT INTO `nodes` VALUES ('良乡南关', '房山站', NULL);
INSERT INTO `nodes` VALUES ('良乡大学城', '房山站', NULL);
INSERT INTO `nodes` VALUES ('良乡大学城北', '房山站', NULL);
INSERT INTO `nodes` VALUES ('良乡大学城西', '房山站', NULL);
INSERT INTO `nodes` VALUES ('芍药居', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('芍药居', '十号线', NULL);
INSERT INTO `nodes` VALUES ('花园桥', '六号线', NULL);
INSERT INTO `nodes` VALUES ('花梨坎', '十五号', NULL);
INSERT INTO `nodes` VALUES ('苏州街', '十号线', NULL);
INSERT INTO `nodes` VALUES ('苏庄', '房山站', NULL);
INSERT INTO `nodes` VALUES ('苹果园', '一号线', NULL);
INSERT INTO `nodes` VALUES ('草房', '六号线', NULL);
INSERT INTO `nodes` VALUES ('草桥', '十号线', NULL);
INSERT INTO `nodes` VALUES ('荣京东街', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('荣昌东街', '亦庄线', NULL);
INSERT INTO `nodes` VALUES ('莲花桥', '十号线', NULL);
INSERT INTO `nodes` VALUES ('菜市口', '七号线', NULL);
INSERT INTO `nodes` VALUES ('菜市口', '四号线', NULL);
INSERT INTO `nodes` VALUES ('蒲黄榆', '五号线', NULL);
INSERT INTO `nodes` VALUES ('蒲黄榆', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('虎坊桥', '七号线', NULL);
INSERT INTO `nodes` VALUES ('褡裢坡', '六号线', NULL);
INSERT INTO `nodes` VALUES ('西二旗', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('西单', '一号线', NULL);
INSERT INTO `nodes` VALUES ('西单', '四号线', NULL);
INSERT INTO `nodes` VALUES ('西四', '四号线', NULL);
INSERT INTO `nodes` VALUES ('西土城', '十号线', NULL);
INSERT INTO `nodes` VALUES ('西小口', '八号线', NULL);
INSERT INTO `nodes` VALUES ('西局', '十号线', NULL);
INSERT INTO `nodes` VALUES ('西直门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('西直门', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('西直门', '四号线', NULL);
INSERT INTO `nodes` VALUES ('西红门', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('西苑', '四号线', NULL);
INSERT INTO `nodes` VALUES ('西钓鱼台', '十号线', NULL);
INSERT INTO `nodes` VALUES ('角门东', '十号线', NULL);
INSERT INTO `nodes` VALUES ('角门西', '十号线', NULL);
INSERT INTO `nodes` VALUES ('角门西', '四号线', NULL);
INSERT INTO `nodes` VALUES ('车公庄', '二号线', NULL);
INSERT INTO `nodes` VALUES ('车公庄', '六号线', NULL);
INSERT INTO `nodes` VALUES ('车公庄西', '六号线', NULL);
INSERT INTO `nodes` VALUES ('车道沟', '十号线', NULL);
INSERT INTO `nodes` VALUES ('达官营', '七号线', NULL);
INSERT INTO `nodes` VALUES ('通州北关', '六号线', NULL);
INSERT INTO `nodes` VALUES ('通州北苑', '八通线', NULL);
INSERT INTO `nodes` VALUES ('通运门', '六号线', NULL);
INSERT INTO `nodes` VALUES ('郝家府', '六号线', NULL);
INSERT INTO `nodes` VALUES ('郭公庄', '九号线', NULL);
INSERT INTO `nodes` VALUES ('郭庄子', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('郭庄子', '十四号西段', NULL);
INSERT INTO `nodes` VALUES ('金台夕照', '十号线', NULL);
INSERT INTO `nodes` VALUES ('金台路', '六号线', NULL);
INSERT INTO `nodes` VALUES ('金台路', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('长春桥', '十号线', NULL);
INSERT INTO `nodes` VALUES ('长椿街', '二号线', NULL);
INSERT INTO `nodes` VALUES ('长阳', '房山站', NULL);
INSERT INTO `nodes` VALUES ('阜成门', '二号线', NULL);
INSERT INTO `nodes` VALUES ('阜通', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('陶然亭', '四号线', NULL);
INSERT INTO `nodes` VALUES ('陶然桥', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('雍和宫', '二号线', NULL);
INSERT INTO `nodes` VALUES ('雍和宫', '五号线', NULL);
INSERT INTO `nodes` VALUES ('霍营', '八号线', NULL);
INSERT INTO `nodes` VALUES ('霍营', '十三号线', NULL);
INSERT INTO `nodes` VALUES ('青年路', '六号线', NULL);
INSERT INTO `nodes` VALUES ('顺义', '十五号', NULL);
INSERT INTO `nodes` VALUES ('首经贸', '十号线', NULL);
INSERT INTO `nodes` VALUES ('马家堡', '四号线', NULL);
INSERT INTO `nodes` VALUES ('马泉营', '十五号', NULL);
INSERT INTO `nodes` VALUES ('高家园', '十四号东段', NULL);
INSERT INTO `nodes` VALUES ('高碑店', '八通线', NULL);
INSERT INTO `nodes` VALUES ('高米店北', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('高米店南', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('魏公村', '四号线', NULL);
INSERT INTO `nodes` VALUES ('黄村火车站', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('黄村西大街', '大兴线', NULL);
INSERT INTO `nodes` VALUES ('黄渠', '六号线', NULL);
INSERT INTO `nodes` VALUES ('鼓楼大街', '二号线', NULL);
INSERT INTO `nodes` VALUES ('鼓楼大街', '八号线', NULL);
INSERT INTO `nodes` VALUES ('龙泽', '十三号线', NULL);

SET FOREIGN_KEY_CHECKS = 1;
